workflows:
  ios-customer:
    name: iOS Customer Release
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ahiaoma.customer
    scripts:
      - name: Pub get
        script: flutter pub get
      - name: Place Firebase plist
        script: |
          if [ -f "$CM_SECURE_FILES_DIR/GoogleService-Info.plist" ]; then
            mkdir -p ios/Runner
            cp "$CM_SECURE_FILES_DIR/GoogleService-Info.plist" ios/Runner/GoogleService-Info.plist
          fi
      - name: Build IPA
        script: flutter build ipa --release --build-name 1.0.0 --build-number $BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration   # uses the API key you’ll add in Codemagic UI
        submit_to_testflight: true
